# Generated by Django 3.2.9 on 2021-11-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('firstName', models.TextField(max_length=255)),
                ('lastName', models.TextField(max_length=255)),
                ('emailAddress', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.TextField(max_length=255)),
                ('itemName', models.TextField(max_length=255)),
                ('author', models.TextField(max_length=255)),
                ('itemsLeft', models.IntegerField()),
                ('rentedCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currState', models.TextField(max_length=10)),
                ('renterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customers')),
            ],
        ),
        migrations.CreateModel(
            name='RentedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items')),
                ('renterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customers')),
            ],
        ),
    ]
